version: "3.8"

services:
  app:
    build:
      context: .
    container_name: book_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    container_name: book_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: book_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: book_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
